default:
  image: python:3.12
  cache:
    paths:
      - .pip-cache/
  before_script:
    - python --version
    - pip install --upgrade pip
    - pip install build twine

stages:
  - build
  - test
  - publish

variables:
  PYTHON_VERSION: "3.12"
  PYPI_URL: "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/packages/pypi"
  TWINE_USERNAME: "__token__"
  TWINE_PASSWORD: "$CI_JOB_TOKEN"
  PROJECT_DIR: "src_iot_libs"
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.pip-cache"
 
build_package:
  stage: build
  script:
    - |
      echo "Extracting tag: ${CI_COMMIT_TAG}"
      # Check if CI_COMMIT_TAG is empty
      if [ -z "${CI_COMMIT_TAG}" ]; then
        echo "Error: CI_COMMIT_TAG is not set. Exiting..."
        exit 1
      fi
    - cd "${PROJECT_DIR}"
    - echo "Updating version in pyproject.toml..."
    - sed -i "s/version\s*=.*/version = \"${CI_COMMIT_TAG}\"/g" pyproject.toml
    - echo "Updated version:"
    - cat pyproject.toml | grep version
    - echo "Building package..."
    - python -m build
    - mkdir -p ../dist
    - mv dist/* ../dist/
  artifacts:
    paths:
      - dist/
  rules:
    - if: $CI_COMMIT_TAG

test_package:
  stage: test
  needs:
    - build_package
  script:
    - pip install pytest
    - pip install dist/*.whl
    - pytest
  rules:
    - if: $CI_COMMIT_TAG

publish_package:
  stage: publish
  needs:
    - test_package
    - build_package
  script:
    - TWINE_PASSWORD=${CI_JOB_TOKEN} TWINE_USERNAME=gitlab-ci-token python -m twine upload --repository-url ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi dist/*
  rules:
    - if: $CI_COMMIT_TAG